name: Deploy to EC2 via CodeDeploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create artifact zip
        run: |
          ARTIFACT_NAME="app-$(date +%s).zip"
          zip -r "$ARTIFACT_NAME" . -x ".git/*"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Upload artifact to S3
        run: |
          aws s3 cp "$ARTIFACT_NAME" "s3://${{ secrets.CODEDEPLOY_BUCKET }}/$ARTIFACT_NAME"

      - name: Create CodeDeploy deployment
        run: |
          ARTIFACT_NAME="${{ env.ARTIFACT_NAME }}"
          aws deploy create-deployment \
            --application-name MyPOCApp \
            --deployment-group-name MyPOCDeploymentGroup \
            --s3-location bucket=${{ secrets.CODEDEPLOY_BUCKET }},key=${ARTIFACT_NAME},bundleType=zip \
            --region us-east-1
